version: "3"


services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/web
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"



  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"

networks:
  apinetwork: