version: "3"


services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/web
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx:/ect/nginx/conf.d/default.conf

networks:
  apinetwork: